services:
  - name: oxyum-social
    type: web
    env: node
    plan: starter
    build:
      dockerfilePath: Dockerfile  # Optional if you're using Docker
    start:
      command: node index.js  # Command to start your app
    routes:
      - path: /
        type: static
        service: oxyum-social
      - path: /url/callback
        type: static
        service: oxyum-social
      - path: /url/login
        type: static
        service: oxyum-social
